### ISSUE TITLE
How can we make it not say paladins.dev

### ISSUE THREAD

**Issue by EliteDaMyth** [paladinspresence/Service#2]
TItle

**Comment by MatthewSH** [comment]
Hey, that’s actually a configuration in the developer dashboard on Discord. I have it included to differentiate the official Paladins one from mine. It’s just an easy way to tell, and make sure people understand it’s not some new feature, or “coming soon” update. Is there something else that could make that more obvious that you can suggest?

**Comment by EliteDaMyth** [comment]
> 
> 
> Hey, that’s actually a configuration in the developer dashboard on Discord. I have it included to differentiate the official Paladins one from mine. It’s just an easy way to tell, and make sure people understand it’s not some new feature, or “coming soon” update. Is there something else that could make that more obvious that you can suggest?

Oh ok Also i had a question does this service run on startup and runs 24/7 or something

**Comment by MatthewSH** [comment]
Ahh shit. I forgot to edit something with it. It checks every second, it used to only check every 2 minutes. Yes it does run in the background 24/7, but will only, in theory, check for the Paladins game in a 2 minute interval (although I may make this configutable). It’s lightweight though. Only using around 8mb of memory during my debugging and testing.

**Comment by EliteDaMyth** [comment]
> 
> 
> Ahh shit. I forgot to edit something with it. It checks every second, it used to only check every 2 minutes. Yes it does run in the background 24/7, but will only, in theory, check for the Paladins game in a 2 minute interval (although I may make this configutable). It’s lightweight though. Only using around 8mb of memory during my debugging and testing.

Oh Thanks for the quick reply ;) You could make something like binding it to the paladins executable so it doesnt have to run every startup. Also how can i compile this myself? I never touched C# before

**Comment by MatthewSH** [comment]
I can’t bind to the exe as that involves code injection and can get your account flagged or banned. I’m trying to be non-invasive. 

You’d need visual studio. I’ll recompile tomorrow with a new release candidate with updated configs.

**Comment by EliteDaMyth** [comment]
Ok Thanks ;) do you have discord? for easier communication
